version: '3'

services:
  php:
    build:
      context: dev
      dockerfile: /images/php/Dockerfile
    volumes:
      - ./public:/var/www/html
    depends_on:
      - postgres

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./public:/var/www/html
      - ./nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${NGINX_PORT:-80}:80

  postgres:
    image: postgres:16.0-alpine
    restart: "always"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    ports:
      - ${POSTGRES_PORT:-6666}:5432